theme: jekyll-theme-tactile
#theme: jekyll-theme-primer
title: Creating static [Choropleth map](https://en.wikipedia.org/wiki/Choropleth_map) images with [Mapbox](https://www.mapbox.com/) and [Shapefiles](https://en.wikipedia.org/wiki/Shapefile).
description: An alternative to [Google map charts](https://developers.google.com/chart/image/docs/gallery/new_map_charts).
